### ISSUE TITLE
Create a guide: How to write a donor acknowledgement

### ISSUE THREAD

**Issue by mmaecruz** [hackforla/revenue#28]
### Overview
We need to create a guide to making donor acknowledgement so that projects can thank donors quickly without having to get org approval for each letter.

### Action Items
- [ ] Gather examples of how other Hack for LA projects have done, adding each example as a link in the resources section
   - [ ] Once done, remove the "TG: Gather Examples" label and add the "TG: Draft Template" label
- [ ] Create a draft template, either in markdown format in this issue or a google doc in the [product management google drive](https://drive.google.com/drive/folders/1lO8k_0Z1UejkuRlNMYlUl2xlqgyBmvrF?usp=sharing)
    - [ ] Once done, remove the "TG: Draft Template" label and add the "TG: Create Guide" label
- [ ] Create a guide on how to use the template 
   - [ ] Once done, remove the "TG: Create Guide" label and add the "TG: Review Guide" label
- [ ] Review the guide with product management communities of practice
   - [ ] Once done, remove the "TG: Review Guide" label and add the "TG: Leadership Review" label
- [ ] Present to Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "TG: Leadership Review" label and add the "TG: Place Guide" label
- [ ] Possibly create an issue template on .github 
   - [ ] Include link to template under resources if you add it as a template in .github

### Resources
- Refer to https://github.com/hackforla/product-management/issues/123 for how to write a guide and the guide template

**Comment by mmaecruz** [comment]
@chelseybeck @Olivia-Chiong Hi Team, here is my "How to Write a donor acknowledgement" guide: [](https://docs.google.com/document/d/1b0wCCw6LGHn-G8XLv99D0-WnZyIn4lqTl2e8qv60LVY/edit?usp=sharing)

**Comment by Olivia-Chiong** [comment]
Discussed with @mmaecruz regarding the next steps, we will draft the letter to Food Oasis donors and include an ask of "Would you like to be informed of upcoming volunteer opportunities including XYZ"

**Comment by mmaecruz** [comment]
Talked to @ExperimentsInHonesty about taking this guide and using the format in the how-to guide: [](https://docs.google.com/document/d/1-8gmeC-wnfM8C8fVvmTP1BLA2WfNjKH_XJrHB1OAV6Q/edit)

**Comment by mmaecruz** [comment]
@hackforla/fundraising This donor acknowledgement guide has been updated to reflect the standard formatting for H4LA guides!

[Find it here](https://docs.google.com/document/d/1Zrk3Hi3ZNfYo1dpe1QYErc7OtVrWYfQse_n3sNVP8T8/edit?usp=sharing)

**Comment by Aditya23soni** [comment]
<details><summary>Prior version of issue</summary>
<p>
### Overview
We need to create a guide to making donor acknowledgement so that projects can thank donors quickly without having to get org approval for each letter.

### Action Items
- [ ] Gather examples of how other Hack for LA projects have done, adding each example as a link in the resources section
   - [ ] Once done, remove the "TG: Gather Examples" label and add the "TG: Draft Template" label
- [ ] Create a draft template, either in markdown format in this issue or a google doc in the [product management google drive](https://drive.google.com/drive/folders/1lO8k_0Z1UejkuRlNMYlUl2xlqgyBmvrF?usp=sharing)
    - [ ] Once done, remove the "TG: Draft Template" label and add the "TG: Create Guide" label
- [ ] Create a guide on how to use the template 
   - [ ] Once done, remove the "TG: Create Guide" label and add the "TG: Review Guide" label
- [ ] Review the guide with product management communities of practice
   - [ ] Once done, remove the "TG: Review Guide" label and add the "TG: Leadership Review" label
- [ ] Present to Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "TG: Leadership Review" label and add the "TG: Place Guide" label
- [ ] Possibly create an issue template on .github 
   - [ ] Include link to template under resources if you add it as a template in .github

### Resources
- Refer to https://github.com/hackforla/product-management/issues/123 for how to write a guide and the guide template
</p>
</details>

**Comment by Aditya23soni** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the [INSERT COP NAME] Repo:</summary>
<p>
<img width="319" alt="Screenshot 2024-10-25 at 7 40 33 PM" src="https://github.com/user-attachments/assets/83761349-c97c-409b-b53a-b15b433a09e1">
</p>
</details>
